// <auto-generated />
using System;
using LogisticIntegration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticIntegration.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226050842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogisticIntegration.Domain.Settlement.ProviderLoad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DocumentaryWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TripSettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TripSettlementId");

                    b.ToTable("ProviderLoad");
                });

            modelBuilder.Entity("LogisticIntegration.Domain.Settlement.TripSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PhysicalNetWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WeighingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TripSettlements", (string)null);
                });

            modelBuilder.Entity("LogisticIntegration.Domain.Settlement.ProviderLoad", b =>
                {
                    b.HasOne("LogisticIntegration.Domain.Settlement.TripSettlement", null)
                        .WithMany("ProviderLoads")
                        .HasForeignKey("TripSettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticIntegration.Domain.Settlement.TripSettlement", b =>
                {
                    b.OwnsOne("LogisticIntegration.Domain.Settlement.DriverPenalty", "Penalty", b1 =>
                        {
                            b1.Property<Guid>("TripSettlementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AppliedMaxPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("MissingWeight")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("TotalPenaltyAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("TripSettlementId");

                            b1.ToTable("TripSettlements");

                            b1.WithOwner()
                                .HasForeignKey("TripSettlementId");
                        });

                    b.Navigation("Penalty");
                });

            modelBuilder.Entity("LogisticIntegration.Domain.Settlement.TripSettlement", b =>
                {
                    b.Navigation("ProviderLoads");
                });
#pragma warning restore 612, 618
        }
    }
}
